[build]
  command = "npm install --legacy-peer-deps && npx expo export --platform web --output-dir dist"
  publish = "dist"

[build.environment]
  EXPO_NO_TELEMETRY = "1"
  NODE_VERSION = "20"
  EXPO_PUBLIC_SUPABASE_URL = "https://wedgjxouawfxinvldxki.supabase.co"
  EXPO_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZGdqeG91YXdmeGludmxkeGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjAzNjcsImV4cCI6MjA2NjMzNjM2N30.Ok_eDp0RJpvey5wpNPE-pw5zzNtPCoEEceQCgsMGonQ"
  EXPO_PUBLIC_RORK_API_BASE_URL = "https://dev-xfcmvrdbt04s7iesuk69v.rorktest.dev"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval'"
