[build]
  command = "npm install && npx expo build:web"
  publish = "web-build"
  environment = { 
    EXPO_NO_TELEMETRY = "1", 
    NODE_VERSION = "20",
    EXPO_PUBLIC_SUPABASE_URL = "https://wedgjxouawfxinvldxki.supabase.co",
    EXPO_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZGdqeG91YXdmeGludmxkeGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjAzNjcsImV4cCI6MjA2NjMzNjM2N30.Ok_eDp0RJpvey5wpNPE-pw5zzNtPCoEEceQCgsMGonQ",
    EXPO_PUBLIC_RORK_API_BASE_URL = "https://dev-xfcmvrdbt04s7iesuk69v.rorktest.dev"
  }

# SPA routing so deep links work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
